/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-tertiary-container": "#bdffdb",
        "on-primary-container": "#efefff",
        "error": "#ba1a1a",
        "surface": "#f8f9ff",
        "surface-container-high": "#dce9ff",
        "tertiary-fixed-dim": "#4edea3",
        "inverse-surface": "#213145",
        "on-tertiary-fixed": "#002113",
        "on-surface-variant": "#434656",
        "surface-container-lowest": "#ffffff",
        "on-secondary-fixed-variant": "#3f465c",
        "inverse-on-surface": "#eaf1ff",
        "on-surface": "#0b1c30",
        "on-secondary": "#ffffff",
        "tertiary": "#006242",
        "on-tertiary": "#ffffff",
        "surface-container": "#e5eeff",
        "secondary-fixed-dim": "#bec6e0",
        "surface-container-highest": "#d3e4fe",
        "surface-dim": "#cbdbf5",
        "error-container": "#ffdad6",
        "inverse-primary": "#b8c3ff",
        "surface-tint": "#124af0",
        "primary-container": "#2e5bff",
        "on-primary": "#ffffff",
        "on-background": "#0b1c30",
        "surface-bright": "#f8f9ff",
        "outline-variant": "#c4c5d9",
        "on-secondary-fixed": "#131b2e",
        "secondary-container": "#dae2fd",
        "secondary-fixed": "#dae2fd",
        "tertiary-container": "#007d55",
        "secondary": "#565e74",
        "primary": "#0040e0",
        "outline": "#747688",
        "primary-fixed-dim": "#b8c3ff",
        "on-tertiary-fixed-variant": "#005236",
        "on-secondary-container": "#5c647a",
        "on-error-container": "#93000a",
        "background": "#f8f9ff",
        "surface-variant": "#d3e4fe",
        "surface-container-low": "#eff4ff",
        "tertiary-fixed": "#6ffbbe",
        "on-primary-fixed": "#001356",
        "primary-fixed": "#dde1ff",
        "on-error": "#ffffff",
        "on-primary-fixed-variant": "#0035be"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "xl": "32px",
        "sm": "8px",
        "xs": "4px",
        "gutter": "20px",
        "md": "16px",
        "base": "4px",
        "container-max": "1440px",
        "lg": "24px"
      },
      fontFamily: {
        "sans": ["Inter", "sans-serif"],
        "headline-lg-mobile": ["Inter", "sans-serif"],
        "display-lg": ["Inter", "sans-serif"],
        "tabular-nums": ["Inter", "monospace"],
        "body-lg": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"]
      },
      fontSize: {
        "headline-lg-mobile": ["24px", { "lineHeight": "32px", "fontWeight": "600" }],
        "display-lg": ["36px", { "lineHeight": "44px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "tabular-nums": ["14px", { "lineHeight": "20px", "fontWeight": "500" }],
        "body-lg": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "headline-md": ["20px", { "lineHeight": "28px", "fontWeight": "600" }],
        "label-md": ["12px", { "lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "600" }],
        "headline-lg": ["28px", { "lineHeight": "36px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "body-md": ["14px", { "lineHeight": "20px", "fontWeight": "400" }]
      }
    },
  },
  plugins: [],
}
